

wellPanel(
  helpText(
    h5("Coursera"),
    tags$img(src ='coursera.png', width = '10%', height = '10%'),
br(),
br(),
a("Coursera", href="https://www.coursera.org/", target="_blank"),
br(),
a("Book Developing Data Products",
  href="https://github.com/seankross/slides/blob/gh-pages/Developing_Data_Products/start/book.pdf",
  target="_blank" ),
br(),
a("Repo DDP",
  href="https://github.com/DataScienceSpecialization/Developing_Data_Products.git",
  target="_blank" ),
hr(),
    h5("Help"),
    tags$img(src ='stackoverflow.png', width = '10%', height = '10%'),
br(),
br(),
a("Questions", href= "http://stackoverflow.com/search?q=shiny", target="_blank"),
hr(),
    h5("Other Links"),
a("R-bloggers", href= "https://www.r-bloggers.com/", target="_blank"),
a("Brian Caffo", href= "http://www.bcaffo.com/", target="_blank"),
br(),
a("Jeff Leek", href= "http://jtleek.com/", target="_blank"),
br(),
a("Roger Peng", href= "https://leanpub.com/u/rdpeng", target="_blank"),
br(),
a("Sean Kross", href= "http://seankross.com/", target="_blank"),
br(),
a("formatR App", href= "https://yihui.shinyapps.io/formatR/", target="_blank"),
br(),
a("SPSS files", href= "https://rpadgett.butler.edu/ps310/classdata.php", target="_blank"),
br(),
a("Andy Field", href= "https://www.youtube.com/user/ProfAndyField/featured", target="_blank"),
br(),
a("Nick Gerdes", href="https://www.youtube.com/user/GerdesNick", target="-blank"),
br(),
a("Quick-R", href="http://www.statmethods.net/index.html", target="_blank"),
br(),
a("Advanced R", href="http://adv-r.had.co.nz/", target="_blank"),
br(),
a("Cookbook for R", href="http://www.cookbook-r.com/", target="_blank" ),
br(),
a("Icons", href="http://fontawesome.io/icons/", target="_blank" ),
br(),
a("graphs on youtube", href="https://www.youtube.com/user/plotlygraph",
  target="_blank" ),
br(),
a("Dean Attali", href="http://deanattali.com/blog/advanced-shiny-tips/",
  target="_blank" ),
hr(),


    h5("Cheatsheets and more"),
    tags$img(src ='R.jpg', width = '10%', height = '10%'),
br(),
br(),
a("googleVis", href="https://cran.r-project.org/web/packages/googleVis/googleVis.pdf", target="_blank"),
br(),
a("shiny and more", href="https://www.rstudio.com/resources/cheatsheets/", target="_blank"),
br(),
a("rio", href="https://cran.r-project.org/web/packages/rio/rio.pdf", target="_blank"),
br(),
a("lubridate", href="https://cran.r-project.org/web/packages/lubridate/lubridate.pdf", target="_blank"),
br(),
a("base R", href="https://www.rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf", target="_blank" ),
br(),
a("advanced R", href="https://www.rstudio.com/wp-content/uploads/2016/02/advancedR.pdf", target="_blank"),
br(),
a("plotly", href="https://plot.ly/r/reference/", target="_blank"),
br(),
a("plotly cookbook", href="https://cpsievert.github.io/plotly_book/", target="_blank"),
br(),
a("DT", href="https://rstudio.github.io/DT/", target="_blank"),
br(),
a("R_color_names", href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf", target="_blank"),
br(),
a("DT", href="http://www.w3schools.com/cssref/default.asp", target="_blank"),
hr(),

h5("Code"),
tags$img(src ='Octocat.jpg', width = '10%', height = '10%'),
br(),
br(),
a("Repo", href="https://github.com/Sadi46", target="_blank"),
hr(),

h5("Licences and terms"),
a("Google Charts", href="https://developers.google.com/chart/interactive/docs/gallery", target="_blank"),
br(),
a("Google APIs Terms of Service", href="https://developers.google.com/terms/", target="_blank"),
br(),
a("creative commons", href="http://creativecommons.org/licenses/by/3.0/", target="_blank"),
br(),
a("Google APIs Terms of Service", href="https://developers.google.com/terms/", target="_blank"),
br(),
a("Apache 2.0", href="http://www.apache.org/licenses/LICENSE-2.0", target="_blank")
))
